from option_contract import OptionContract, OptionType
from black_scholes import black_scholes_price


def implied_volatility_bisection(
        market_price: float,
        spot: float,
        strike: float,
        time_to_maturity: float,
        risk_free_rate: float,
        dividend_yield: float = 0.0,
        option_type: OptionType = "call",
        lower_vol=1e-6,
        upper_vol=5.0,
        tolerance: float = 1e-8,
        max_iterations: int = 200,
) -> float:
    # """Solve implied volatility from a market option price using bisection."""
    if market_price <= 0:
        raise ValueError("Market price must be positive")

    def price_at(vol: float) -> float:
        contract = OptionContract(
            spot=spot,
            strike=strike,
            time_to_maturity=time_to_maturity,
            risk_free_rate=risk_free_rate,
            volatility=vol,
            dividend_yield=dividend_yield,
            option_type=option_type,
        )
        return black_scholes_price(contract)

    low_price = price_at(lower_vol)
    high_price = price_at(upper_vol)

    if not (low_price <= market_price <= high_price):
        raise ValueError("Market price is outside the range generated by the volatility bounds")

    low = lower_vol
    high = upper_vol

    for _ in range(max_iterations):
        mid = 0.5 * (low + high)
        mid_price = price_at(mid)

        if abs(mid_price - market_price) < tolerance:
            return mid
        if mid_price < market_price:
            low = mid
        else:
            high = mid

    return 0.5*(low + high)